apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "B2305573"
  SECRET_KEY: "24b0a8c7ad925a3e24e99ce36b3c53b2b33b542098611cb14fc02370c44da390"

  USERS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/user_db"
  COURSES_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/course_db"
  QUIZS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/quiz_exam_db"
  LEARNING_PROGRESS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/learning_progress_db"
  DATABASE_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/config_db"
  # "<giữ nguyên giá trị cũ hoặc tạo mới bằng: openssl rand -hex 32>"
  # URL nội bộ để các service gọi lẫn nhau (dùng tên Service trong cluster)
  BACKEND_USER_URL: "http://user-service:8000"
  BACKEND_COURSE_URL: "http://course-service:8001"
  BACKEND_QUIZ_EXAM_URL: "http://quiz-exam-service:8002"
  BACKEND_LEARNING_PROGRESS_URL: "http://learning-progress-service:8003"
  FRONTEND_HOST: "https://10.7.5.6:3000"
  BACKEND_CORS_ORIGINS: "https://10.7.5.6>"

  STORAGE_API_URL: "http://course-service:8001"
  CLIENT_ID: "<Google OAuth Client ID>"
  CLIENT_SECRET_KEY: "<Google OAuth Client Secret>"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_DAYS: "1"

  ADMIN_KEY: "change-me-please"