apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: B2305573
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: B2305573
  SECRET_KEY: 24b0a8c7ad925a3e24e99ce36b3c53b2b33b542098611cb14fc02370c44da390